### ISSUE TITLE
how to get spring.oauth2.sso.resource.jwt.keyValue

### ISSUE THREAD

**Issue by leon** [spring-cloud-samples/sso#4]
Hi!
I've implemented the auth server, config server and got everything up and running.
But I'm having troubles with the public private keys.

I've generated a new keystore with
`keytool -keystore keystore.jks -genkey -alias client`

has the application.yml value `spring.oauth2.sso.resource.jwt.keyValue` got something to do with the keystore i created, and how do I get the https://github.com/spring-cloud-samples/sso/blob/master/src/main/resources/application.yml#L25-L27 value?

**Comment by dsyer** [comment]
The keyValue is a PEM-encoded public key (or key pair for an auth server). You can export it from your keystore or you can curl it from an auth server that's using your keystore (if it's exposing the endpoint), e.g. this one: https://github.com/spring-cloud-samples/authserver.
