### ISSUE TITLE
fails with spring-cloud-samples/authserver

### ISSUE THREAD

**Issue by doom777** [spring-cloud-samples/sso#7]
Looks like this:

home

dashboard

login

logout

Authenticated: <html> <head> <link rel="stylesheet" href="css/wro.css"/> </head> <body> <div class="container"> <form role="form" action="login" method="post"> <div class="form-group"> <label for="username">Username:</label> <input type="text" class="form-control" id="username" name="username"/> </div> <div class="form-group"> <label for="password">Password:</label> <input type="password" class="form-control" id="password" name="password"/> </div> <input type="hidden" id="csrf_token" name="_csrf" value="6f799617-eac2-44f1-a326-2e04e5e14e40"/> <button type="submit" class="btn btn-primary">Submit</button> </form> </div> <script src="js/wro.js" type="text/javascript"></script> </body> </html>

 
Home

**Comment by dsyer** [comment]
What looks like this? How is it is a "failure"?
